// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qnxnasvdxioyelmaflbn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFueG5hc3ZkeGlveWVsbWFmbGJuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY5NTczNjksImV4cCI6MjA2MjUzMzM2OX0.RRspyt_sRFQgKvAFzzKLkWl2DrTaQhjyhYCpdk9vOKY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);